### ISSUE TITLE
Please support python3

### ISSUE THREAD

**Issue by yurivict** [SRI-CSL/libpoly#16]
Currently only python 2 is supported.

**Comment by dddejan** [comment]
I agree this would be nice. I will take a look on how to do this, but it's not a priority at the moment.

My guess is that the differences to the Python2 interface shouldn't be big if anyone is interested in helping.

**Comment by dddejan** [comment]
Reference: https://docs.python.org/3/howto/cporting.html

**Comment by dddejan** [comment]
@yurivict the python3 support has been merged. let us know if there are any issues.
