### ISSUE TITLE
lp_upolynomial_extended_gcd on lp_Z

### ISSUE THREAD

**Issue by nafur** [SRI-CSL/libpoly#28]
From the comments of `lp_upolynomial_gcd` and `lp_upolynomial_extended_gcd` I'd expect that they can be applied in the same situations. After all, the comments are almost identical.
However, `lp_upolynomial_gcd` allows coefficients from `lp_Z` while `lp_upolynomial_extended_gcd` requires coefficients from a prime ring: https://github.com/SRI-CSL/libpoly/blob/20ae0b6803dc216922dcfc7e3383da720d434439/src/upolynomial/upolynomial.c#L1047
I'd suggest to either allow `lp_Z` for `lp_upolynomial_extended_gcd` as well or modify the comment accordingly.

**Comment by dddejan** [comment]
Yup, this is confusing.

1. `upolynomial_gcd_euclid` uses exact division so it needs a field
2.`upolynomial_gcd_subresultant` works for Z
3. `lp_upolynomial_gcd` will switch on 1. and 2. to get the result
4. `lp_upolynomial_extended_gcd` only relies on 1., so it needs a field

It's been a while, but it seems like the doc needs to be fixed.

**Comment by dddejan** [comment]
It's not clear that some of these API functions are actually useful. 

They are exposed in the C API for flexibility and testing but feel free to exclude them from C++ API.

**Comment by dddejan** [comment]
I'm closing this. Reopen if it's not resolved.
