### ISSUE TITLE
Proper ordering on intervals

### ISSUE THREAD

**Issue by nafur** [SRI-CSL/libpoly#39]
I'm trying to build reasonably consistent comparison operators based on `lp_interval_cmp()`, but struggle with what appears to be inconsistent behavior. My current approach is to implement the operators as follows:

    <: lp_interval_cmp() is one of LT_NO_INTERSECT, LT_WITH_INTERSECT, LT_WITH_INTERSECT_I1
    <=: lp_interval_cmp() is one of LT_NO_INTERSECT, LT_WITH_INTERSECT, LT_WITH_INTERSECT_I1, LEQ_WITH_INTERSECT_I2, EQ

For `<` I figured that the ordering could be `\forall l \in lhs. \exists r \in rhs. l < r` (but not `\forall r \in rhs. \exists l \in lhs. l < r`)
For `<=`, however, the analogous `\forall l \in lhs. \exists r \in rhs. l <= r` does not work, as `(4,6) <= (3,6)` is false. The alternative `\forall r \in rhs. \exists l \in lhs. l <= r` does not work as well, as `(1,8) <= (3,6)` is false.

One could argue that both need to hold: `\forall l \in lhs. \exists r \in rhs. l <= r && \forall r \in rhs. \exists l \in lhs. l <= r`, but then why is `(4,5) <= (3,6)`?
The common thing of all the examples above seems to be that one covers the other....

I'm aware that ordering intervals is both a weird beast and oftentimes requires custom orderings anyway, but if we offer a "default ordering", it should be somewhat consistent.

**Comment by dddejan** [comment]
I don't think I ever had a need to order intervals unless they were disjoint. The `lp_interval_cmp` function is used I think for managing disjoint sets of intervals (e.g., adding an interval to a disjoint set at the right place, see `lp_feasibility_set_intersect_with_status`). 

If I were to have a generic order, I would just order the intervals lexicographically on the pair (lb, ub), with details for bound types (strict/non-strict). I think `lp_interval_cmp` gives that order:

- I1 < I2 if lp_interval_cmp(I1, I2) in
```
LP_INTERVAL_CMP_LT_NO_INTERSECT,
LP_INTERVAL_CMP_LT_WITH_INTERSECT,
LP_INTERVAL_CMP_LT_WITH_INTERSECT_I1,
LP_INTERVAL_CMP_LEQ_WITH_INTERSECT_I2,
```
- l1 == l2 if lp_interval_cmp(I1, I2) in 
```
LP_INTERVAL_CMP_EQ
```
- I1 > I2 if lp_interval_cmp(I1, I2) in 
```
LP_INTERVAL_CMP_GEQ_WITH_INTERSECT_I1,
LP_INTERVAL_CMP_GT_WITH_INTERSECT_I2,
LP_INTERVAL_CMP_GT_WITH_INTERSECT,
LP_INTERVAL_CMP_GT_NO_INTERSECT
```

In the `lp_interval_cmp_t` enumeration I think the `LT`, `LEQ`, ..., correspond to the interval upper bound comparison.

**Comment by nafur** [comment]
Ah, okay. I guess a lexicographic ordering would make more sense.
However, we should then have `(1,8) < (3,6)` (as `1<3`) and `lp_interval_cmp` yields `LP_INTERVAL_CMP_GT_WITH_INTERSECT_I2` on that one.
Interestingly, `(3,6) < (1,8)` would be true as it yields `LP_INTERVAL_CMP_LT_WITH_INTERSECT_I1`. Maybe these are mixed up here? https://github.com/SRI-CSL/libpoly/blob/master/src/interval/interval.c#L1128

**Comment by dddejan** [comment]
Wow, that looks fishy, let me refresh what's going on here.

**Comment by dddejan** [comment]
Yeah what I said above is not correct, the comparison is based on upper bound first, as described in the function comments. So the proposed order would still be lexicographic, but on upper bound first.

```c
  /* I1: (  )
   * I2:      (   ) */
  LP_INTERVAL_CMP_LT_NO_INTERSECT, -----> ub is <, so <
  /* I1: (   )
   * I2:   (   )    */
  LP_INTERVAL_CMP_LT_WITH_INTERSECT,  -----> ub is <, so <
  /* I1: (   )
   * I2: (     )    */
  LP_INTERVAL_CMP_LT_WITH_INTERSECT_I1,  -----> ub is <, so <
  /* I1: (     ]
   * I2:   (   ]    */
  LP_INTERVAL_CMP_LEQ_WITH_INTERSECT_I2,  -----> ub is ==, lb is <, so <
  /* I1: (   ]
   * I2: (   ]      */
  LP_INTERVAL_CMP_EQ, -----> ==
  /* I1:   (   ]
   * I2: (     ]    */
  LP_INTERVAL_CMP_GEQ_WITH_INTERSECT_I1, -----> ub is ==, lb is >, so >
  /* I1: (       )
   * I2: (    )     */
  LP_INTERVAL_CMP_GT_WITH_INTERSECT_I2, -----> ub is >, so >
  /* I1:   (    )
   * I2: (    )     */
  LP_INTERVAL_CMP_GT_WITH_INTERSECT, -----> ub is >, so >
  /* I1:      (   )
   * I2: (  )       */
  LP_INTERVAL_CMP_GT_NO_INTERSECT -----> ub is >, so >
```

The reason for this order was that it simplifies intersection when scanning from left to right.

I hope this is correct :)

**Comment by nafur** [comment]
I see. As this seems pretty counter-intuitive to me, I'll use `lp_interval_cmp_lower_bounds` and `lp_interval_cmp_upper_bounds` to construct the default order... thanks for the explanation!
