### ISSUE TITLE
Why are libpicpoly.a  libpicpolyxx.a not installed?

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/libpoly#53]
Is there any reason why I don't get my PIC archives when I build them and do a 
```
make install
```

**Comment by nafur** [comment]
I'd be in favor of changing this as well. (Right now, we do the following in cvc5: https://github.com/cvc5/cvc5/blob/master/cmake/FindPoly.cmake#L92)

**Comment by dddejan** [comment]
Oh there is no reason. Feel free to add it.

**Comment by ianamason** [comment]
Hope this helps @nafur

**Comment by ahmed-irfan** [comment]
@ianamason Can we close this? I think this is fixed...

**Comment by ianamason** [comment]
We can!
