### ISSUE TITLE
Implement `open_memstream` on Windows

### ISSUE THREAD

**Issue by RyanGlScott** [SRI-CSL/libpoly#65]
Currently, `libpoly` provides a shim implementation of `open_memstream` on Windows that simply returns `NULL`:

https://github.com/SRI-CSL/libpoly/blob/0e41e05da2ec79875104e73b0e334b8595381200/src/utils/open_memstream.c#L51-L60

This shim implementation is used in `lp_algebraic_number_to_string` here:

https://github.com/SRI-CSL/libpoly/blob/06d4e3c1a1c18a5253398889c296ef787a3ce1cd/src/number/algebraic_number.c#L505-L512

But because `open_memstream` returns `NULL`, this causes a segfault when trying to print out the `FILE*` in `lp_algebraic_number_print`, as observed in cvc5/cvc5#9567.

Ideally, `open_memstream` would do something sensible in terms of the Win32 API. An example of this can be found in the [`fmem`](https://github.com/Snaipe/fmem) library, which implements a function very similar to `open_memstream` [here](https://github.com/Snaipe/fmem/blob/b73b3d8b570c2f79df5a0b071efba392a82ddcd7/src/fmem-winapi-tmpfile.c#L89-L124).

**Comment by ianamason** [comment]
We would welcome a pull request :-)

**Comment by RyanGlScott** [comment]
A couple of questions:

* If I copy over the implementation from `fmem`, how should I credit the authors of that code? (It's [licensed under the MIT license](https://github.com/Snaipe/fmem/blob/b73b3d8b570c2f79df5a0b071efba392a82ddcd7/LICENSE).)
* How do I run the `libpoly` test suite to make sure that it is working as expected?

**Comment by ianamason** [comment]
1. You could follow the example of open_memstream and put it in src/utils with the license in the code.
2. I'll let @ahmed-irfan answer the testing question. Its been a while since I futzed with it.

**Comment by ahmed-irfan** [comment]
Also, it would be nice to add a test in https://github.com/SRI-CSL/libpoly/tree/master/test/polyxx.

**Comment by RyanGlScott** [comment]
After doing some more reading into [`fmem`](https://github.com/Snaipe/fmem), I've realized that it isn't quite a drop-in replacement for `open_memstream`, as it requires augmenting the `FILE*` with a `struct` that stores some additional scaffolding. That's not a deal-breaker in and of itself, however, as the API is still pretty similar to that of `open_memstream`. There are two more quirks of `fmem` that are more concerning:

1. It's not clear to me what the proper conventions are for using [`fmem_term`](https://github.com/Snaipe/fmem/blob/b73b3d8b570c2f79df5a0b071efba392a82ddcd7/src/fmem-winapi-tmpfile.c#L29-L36) are. This appears to be important for cleaning up temporary file handles, but you are seemingly _not_ allowed to call `fmem_term` before accessing the contents of the string whose contents are mapped from the `fmem` itself. (I tried doing this, and it segfaults.)

   On the other hand, all the uses of `open_memstream` in `libpoly` involve temporary files that are local to specific functions, such as `lp_algebraic_number_to_string`. This means that the only place where we could feasibly call `fmem_term` is within `lp_algebraic_number_to_string` itself, but that will cause issues for the reasons described above. We could just _not_ call `fmem_term`, I suppose, but there is a possibility that that could leak file handles.
2. `open_memstream` is intended to update the contents of the memory-mapped string after invoking `fflush` or `ffclose` on the `FILE*`. In practice, I've found that `fmem_open` doesn't quite follow the same pattern: it updates the memory-mapped file after an `fflush`, but _not_ after an `fclose`. Notably, `libpoly` only ever uses `fclose`, not `fflush`. This isn't a huge discrepancy, as we could add a call to `fflush` before each `fclose` in `libpoly`, but it feels strange to have to do this in the first place.
3. After reading the code in `fmem` a bit more closely, I think it's a bit overwrought in certain places. For instance, it uses a [surprising amount of code](https://github.com/Snaipe/fmem/blob/b73b3d8b570c2f79df5a0b071efba392a82ddcd7/src/fmem-winapi-tmpfile.c#L52-L74) just for the sake of creating a temporary file. I really have no clue why this is as complicated as it is, as I think a simple call to [`GetTempFileName`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettempfilenamea) would work just as well and be much simpler.

   I haven't fully inspected the rest of the code, but that was one thing that jumped out at me upon a quick glance.
4. Most importantly, the code in `fmem` hasn't been updated since 2017 and appears to be unmaintained. I'm not sure if I'd want to rely on this going forward.

Luckily, `fmem` isn't the only `open_memstream`-for-Windows implementation in town. The `mesa` package (also MIT-licensed) also rolls its own version of `open_memstream` [here](https://github.com/Mesa3D/mesa/blob/e4e4ba23047a0f2f2578691456e487fba2013f43/src/util/memstream.c). Unlike `fmem`:

1. There is no ambiguity about the idiomatic way to close a `struct u_memstream`: you just call `u_memstream_close` after writing what you need to the file. Moreover, I have verified that you _can_ access the contents of the memory-mapped string after a call to `u_memstream_close`.
2. A call to `u_memstream_close` behaves like `fclose` in the `open_memstream` setting, which works well for `libpoly`'s needs.
3. The `u_memstream` code is much simpler.
4. Most importantly, `u_memstream` is actively maintained (insofar as `mesa` is actively maintained).

I'm going to try using `u_memstream` in `libpoly` and see how it fares. Again, `u_memstream` isn't quite a drop-in replacement for `open_memstream`, but it's close enough that I don't think the changes will be very significant.

**Comment by RyanGlScott** [comment]
I've submitted #66 with a fix.

**Comment by RyanGlScott** [comment]
Fixed in #66.
