### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by vrcamillo** [SRI-CSL/libpoly#69]
In cvc5, we have been using an unreleased commit version of libpoly. The last release (0.1.11) was on 2021 and there have been some bug fixes and feature additions to libpoly's main branch since then. Some of our users are unable to build cvc5 if they install the latest version of libpoly in their system. Could you consider releasing a new version?

**Comment by ianamason** [comment]
This sounds like a job for you now @ahmed-irfan. Do you need me to show you the ropes? It should also mean updating the homebrew formula, too.

**Comment by ahmed-irfan** [comment]
@vrcamillo
we made a new release of libpoly and also updated the homebrew formula. Please let us know if things don't work on your end.

**Comment by vrcamillo** [comment]
Thanks for the quick response, @ahmed-irfan. 

I came across an issue when setting cvc5 to use the new version. When building libpoly as a shared library, the files are suffixed with the wrong version, which might be misleading to users: `libpoly.so.0.1.11`.

I believe that could be solved by changing `LIBPOLY_VERSION_PATCH` in `libpoly/CMakeLists.txt:17`:
```cmake
set(LIBPOLY_VERSION_PATCH 11)
```
to 
```cmake
set(LIBPOLY_VERSION_PATCH 12)
```

Could you make that update?

**Comment by ahmed-irfan** [comment]
Done! 

Please check now.

**Comment by vrcamillo** [comment]
Thanks. Are the brew tap and git repository tags updated?

**Comment by vrcamillo** [comment]
I'm seeing here that https://github.com/SRI-CSL/libpoly/tree/v0.1.12 does not include that change. 
Could you change the 0.1.12 tag to the new commit or maybe release a new 0.1.13?

**Comment by ahmed-irfan** [comment]
I made a newer release. 
Thanks for checking this!

**Comment by ianamason** [comment]
I deleted the buggy version. I would have moved the tag, rather than created a newer version, but I have to fight against hoarding tendencies.
